version: 2

workflows:
  version: 2
  test:
    jobs:
      - tests

jobs:
  tests:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: Run Tests
          command: go test -coverprofile=coverage.out
      - run:
          name: Generate Coverage Report
          command: go tool cover -html=coverage.out -o coverage.html
      - store_artifacts:
          path: coverage.html
